-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 17:02:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgev` DEFAULT CHARACTER SET utf8 ;
USE `sgev` ;

-- -----------------------------------------------------
-- Table `sgev`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgev`.`Funcionarios` (
  `id_funcionario` INT NOT NULL,
  `nome_funcionario` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `salario` FLOAT NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `senha` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgev`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgev`.`Produtos` (
  `id_produto` INT NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `data_max_troca` INT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgev`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgev`.`Clientes` (
  `id_cliente` INT NOT NULL,
  `cpf` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `nome_cliente` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgev`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgev`.`Vendas` (
  `id_vendas` INT NOT NULL,
  `data_compra` DATE NULL,
  `id_funcionario` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_produto` INT NOT NULL,
  PRIMARY KEY (`id_vendas`),
  INDEX `fk_Vendas_Funcionarios1_idx` (`id_funcionario` ASC) VISIBLE,
  INDEX `fk_Vendas_Clientes1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_Vendas_Produtos1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Vendas_Funcionarios1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `sgev`.`Funcionarios` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_Clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `sgev`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_Produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `sgev`.`Produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgev`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgev`.`Fornecedor` (
  `id_fornecedor` INT NOT NULL,
  `nome_fornecedor` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `produtos` TEXT(100) NULL,
  PRIMARY KEY (`id_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgev`.`Entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgev`.`Entregas` (
  `id_entrega` INT NOT NULL,
  `nome_distribuidora` VARCHAR(45) NULL,
  `previsao_entrega` DATE NULL,
  `id_vendas` INT NOT NULL,
  PRIMARY KEY (`id_entrega`),
  INDEX `fk_Entregas_Vendas1_idx` (`id_vendas` ASC) VISIBLE,
  CONSTRAINT `fk_Entregas_Vendas1`
    FOREIGN KEY (`id_vendas`)
    REFERENCES `sgev`.`Vendas` (`id_vendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sgev`.`Funcionarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgev`;
INSERT INTO `sgev`.`Funcionarios` (`id_funcionario`, `nome_funcionario`, `cpf`, `salario`, `cargo`, `rua`, `bairro`, `numero`, `cidade`, `senha`) VALUES (1, 'Antônio ', '346.888.555-76', 1000, 'GERENTE', 'Rua Alvarez', 'Jardim 2', '562', NULL, 'f6ff5adab5180a3d10ffb611f2caddd0a2b0922bde398ad186e946480bec3943');
INSERT INTO `sgev`.`Funcionarios` (`id_funcionario`, `nome_funcionario`, `cpf`, `salario`, `cargo`, `rua`, `bairro`, `numero`, `cidade`, `senha`) VALUES (66, 'God ', '344.888.554-76', 1000, 'ATENDENTE', 'Rua Alvarez', 'Jardim 2', '562', NULL, 'c25e6df7c32171209abf3d7a2c274611a7761627884789374c2531e8477d1af8');

COMMIT;



-- -----------------------------------------------------
-- Data for table `sgev`.`Produtos`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgev`;
INSERT INTO `sgev`.`Produtos` (`id_produto`, `nome_produto`, `preco`, `data_max_troca`) VALUES (1, 'Celular', 1200, 25);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgev`.`Clientes`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgev`;
INSERT INTO `sgev`.`Clientes` (`id_cliente`, `cpf`, `data_nascimento`, `nome_cliente`, `rua`, `bairro`, `numero`, `cidade`) VALUES (1, '267.435.432-54', '1978-03-17', 'Júlio Arnaldo', 'Rua Andori', 'Imperador', '78', 'Araraquara ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgev`.`Vendas`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgev`;
INSERT INTO `sgev`.`Vendas` (`id_vendas`, `data_compra`, `id_funcionario`, `id_cliente`, `id_produto`) VALUES (1, '2023-12-23', 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgev`.`Fornecedor`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgev`;
INSERT INTO `sgev`.`Fornecedor` (`id_fornecedor`, `nome_fornecedor`, `cnpj`, `telefone`, `email`, `produtos`) VALUES (1, 'Samsungo', '87.233.727/0001-05', NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgev`.`Entregas`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgev`;
INSERT INTO `sgev`.`Entregas` (`id_entrega`, `nome_distribuidora`, `previsao_entrega`, `id_vendas`) VALUES (1, 'JáChegou', '2023-12-30', 1);

COMMIT;

